### ISSUE TITLE
API suggestion

### ISSUE THREAD

**Issue by zhaoyao91** [Cogoport/cogo-toast#28]
It's bad style to return different things based on the options or state.

The toast functions could be designed to return an object to represent the toast instance with fields such as `close` and `promise`. This way, the original features are kept, but the behavior is more consistent.

More, the `onClick` could be simplified to a more general zero-arg function:

```
const {close} = assert.info('xxx', {onClick: () => close()})
```

Nice package!

**Comment by anmolmahatpurkar** [comment]
Agreed. Changed in #33
