### ISSUE TITLE
Feature to close the toast manually

### ISSUE THREAD

**Issue by ratnajeetshyamkunwar** [Cogoport/cogo-toast#4]

**Comment by anmolmahatpurkar** [comment]
Hey, @ratnajeetshyamkunwar that sounds like a good option. I will try to get it this weekend. Meanwhile, if you would like to contribute, you are welcome to create a PR to add the feature. I will be happy to review

**Comment by FaiChou** [comment]
```javascript
const closeLoading = cogoToast.loading('uploading..', { hideAfter: 0 });
// after logic
closeLoading();
```

Isn't this suit for your situation?

**Comment by yuritoledo** [comment]
Is this working?

**Comment by anmolmahatpurkar** [comment]
@yuritoledo Yes it works :)

**Comment by yuritoledo** [comment]
amazing, congratz :)

**Comment by tamert** [comment]
not working to me

const closeLoading = cogoToast.loading('logining..', { hideAfter: 0 });
        userService.login(username, password).
            then(
                user => {
                    closeLoading();
                    cogoToast.success('Login!.');
                    dispatch(success(username));
                },
                error => {
                    closeLoading();
                    dispatch(failure(error.toString()));
                    cogoToast.error(error.toString());
                }
            );
    };

Unhandled Rejection (TypeError): closeLoading is not a function

**Comment by yuritoledo** [comment]
@tamert what version are you using?

**Comment by DedaDev** [comment]
> ```js
> const closeLoading = cogoToast.loading('uploading..', { hideAfter: 0 });
> // after logic
> closeLoading();
> ```
> 
> Isn't this suit for your situation?

What if I want a close button inside of toast?
