### ISSUE TITLE
Updating text while toast is showing

### ISSUE THREAD

**Issue by luniki** [Cogoport/cogo-toast#41]
Is it possible to update the text while the toast is already showing? 

Something like this:

```
  const LoadingText = props => <div>Loading for {props.text}%</div>;

  // [...]

  const [percent, setPercent] = useState(0);
  useEffect(() => {
    const interval = setInterval(() => {
      setPercent(lastPercent => lastPercent + 1);
    }, 1000);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    toast.loading(
        <LoadingText text={percent} />,
      { hideAfter: 0 }
    );
  }, [percent]);
```

**Comment by luniki** [comment]
The example is obviously wrong. I looked at the code and I guess that there is no way to update Toasts that are already in the ToastContainer. Is this correct?

**Comment by anmolmahatpurkar** [comment]
I don't this is possible with the way this package is currently designed. Trying to support this would require a redesign to a large extent. I don't think I can get time to work on it for a while.

Closing for now, but would love it if you will be willing to give it a go and submit a PR if time permits you.
