### ISSUE TITLE
Odd issue with SVG icon

### ISSUE THREAD

**Issue by MuTLY** [Cogoport/cogo-toast#44]
Depending on screen size, the icon shows different sizes.

![image](https://user-images.githubusercontent.com/777006/69833631-e9897600-1213-11ea-84a4-3a64ca9f2440.png)

![image](https://user-images.githubusercontent.com/777006/69833650-06be4480-1214-11ea-82fc-c95d80b8e443.png)

I haven't touch the original CSS and I'm having a hard time finding the cause of this.

**Comment by MuTLY** [comment]
The more text added to the toaster, the smaller the icon. Solution: adding a `min-width` to the `svg` CSS rule with the same size of the icon element (18px) fixes this behavior.

**Comment by anmolmahatpurkar** [comment]
Fixed in v4.1.3 with #46
