### ISSUE TITLE
document.body.append is undefined on Chrome 47

### ISSUE THREAD

**Issue by hongzzz** [Cogoport/cogo-toast#45]
https://github.com/Cogoport/cogo-toast/blob/6d7713aa9c62846ddc496773f7b33611dcfb0d3a/src/index.js#L17

![image](https://user-images.githubusercontent.com/25585061/69939106-fbbc2a80-1519-11ea-822b-ada8fc1f661a.png)

Replace it with appendChild will be better?

**Comment by anmolmahatpurkar** [comment]
Fixed in v4.1.3 with #46
