### ISSUE TITLE
useEffect not cancelling timeouts.

### ISSUE THREAD

**Issue by revickulous2001** [Cogoport/cogo-toast#49]
I have just installed this project, and I am receiving the following error/warning:

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
>    in Toast (created by ToastContainer)

This seems to be due to the fact that the timeouts aren't cancelled in the `useEffect` hook in the `Toast` component.

**Comment by anmolmahatpurkar** [comment]
Fixed in v4.2.2
