### ISSUE TITLE
closing with some function

### ISSUE THREAD

**Issue by MehdiAghighi** [Cogoport/cogo-toast#54]
i want a toast to be closed after my api call finished, not after an amount of time.
what can i do ?
thanks for your great library

**Comment by anmolmahatpurkar** [comment]
On execution, cogoToast returns an object with a hide function. Be sure to mark hideAfter as 0 in the options to never hide the toast unless the hide function is called.

See Example Below

```js
const { hide } = cogoToast.success('This is a success message.', { hideAfter: 0 });

// When your API call completes.
hide();
```
