### ISSUE TITLE
I need an API to configure custom colors

### ISSUE THREAD

**Issue by eugle** [Cogoport/cogo-toast#59]
I want to customize success,error,info... Is it possible to add this API

**Comment by anmolmahatpurkar** [comment]
@eugle Actually, this is already possible but was not documented. I added it to the README. 

You can follow this method to define custom colors for different types of toasts.
https://github.com/Cogoport/cogo-toast/blob/master/README.md#customize-each-type-of-toast-seperately

**Comment by eugle** [comment]
I want something like this, including the color of the icon icon that can be SVG

![image](https://user-images.githubusercontent.com/24447931/80915948-12480580-8d88-11ea-9d22-f0d81ebf686b.png)

The actual use is this

Toast.GlobalColor({ success: ’#666‘}）
