### ISSUE TITLE
Could not find a declaration file for module 'cogo-toast'

### ISSUE THREAD

**Issue by chrysb** [Cogoport/cogo-toast#6]
Looks like a great library, but after installing I get this:

`Could not find a declaration file for module 'cogo-toast'. '/path/to/node_modules/cogo-toast/dist/index.js' implicitly has an 'any' type.`

Do you support TypeScript?

I did:
`npm install --save cogo-toast`
`import cogoToast from 'cogo-toast';`

Thanks!

**Comment by anmolmahatpurkar** [comment]
Thank you. Glad you like it.

It is most likely searching for a `typings` files. We don't support typescript as of now. I will try to add the support in a future release but can't give an eta as of now.

**Comment by chrysb** [comment]
For posterity, I did figure out a solution by creating an `index.d.ts` file in my root with the line `declare module 'cogo-toast';`.

**Comment by anmolmahatpurkar** [comment]
Merged in #12
