### ISSUE TITLE
How to change styling of text

### ISSUE THREAD

**Issue by wmlutz** [Cogoport/cogo-toast#7]
My site uses a UI framework. We want a light text on a dark background. So this is what my toasts look like:
![screen shot 2019-03-07 at 8 01 38 am](https://user-images.githubusercontent.com/6496048/53958656-a13b8e00-40af-11e9-94a6-08538a412d8e.png)

Any suggestions on how to configure styling to the toast component? Or classnames I could use?

**Comment by wmlutz** [comment]
If anyone else has this problem I solved it with setting text color for #ct-container. Doesn't fix the header issue though.

**Comment by jsargeim** [comment]
Is this possible? I want to change font and style as well.

**Comment by tolgas-adventures-in-wonderland** [comment]
Same Problem. Any Solutions?

**Comment by anmolmahatpurkar** [comment]
Merged in #12 

You can now extend the `ct-toast` class name and add your custom styling in v2.0.0.

Refer https://github.com/Cogoport/cogo-toast#custom-styling
