### ISSUE TITLE
React v17 compatible

### ISSUE THREAD

**Issue by stefensuhat** [Cogoport/cogo-toast#71]

**Comment by dayvista** [comment]
+1 for this

**Comment by lemihthien** [comment]
the same issue

**Comment by brayn003** [comment]
Can you please tell me what exactly is the issue?

**Comment by dayvista** [comment]
@brayn003 When running `npm install` on this package, the installation fails unless the `--force` tag is used. The package is asking for `react: ^16.0.0` as a peer dependency, and doesn't register v17 of React as valid as a result

**Comment by oliemansm** [comment]
This project seems pretty dead unfortunately... Does somebody have a fork where this has been fixed and published that one to npm?
