### ISSUE TITLE
How to change the height of toast

### ISSUE THREAD

**Issue by WuYufeng233** [Cogoport/cogo-toast#8]
The height of toast(without heading) in your [demo ](https://cogoport.github.io/cogo-toast/)  is 45px, but when I use it in my project, its height is more than 45px(without heading), maybe 65px, which is weird. It seems that it's not likely to custom the height of toast. Why does it happen and any solution to custom the height?

**Comment by eugle** [comment]
Same question

**Comment by anmolmahatpurkar** [comment]
Merged in #12 

You can now extend the `ct-toast` class name and add your custom styling in v2.0.0.

Refer https://github.com/Cogoport/cogo-toast#custom-styling
